name: GitHub Actions
on: [ push ]
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: sampledb
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_HOST: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Update apt-get
        run: |
          apt-get -q update 1> /dev/null

      - name: Install PostgreSQL client
        run: |
          apt-get -q install --yes postgresql-client 1> /dev/null

      - name: Checkout React
        uses: actions/checkout@v3
        with:
          repository: JudeaDumont/react-app-frontend
          path: ./react

      - name: Checkout Selenium/Cucumber
        uses: actions/checkout@v3
        with:
          repository: JudeaDumont/SeleniumWithReact
          path: ./SeleniumWithReact

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 1> /dev/null
          dpkg -i google-chrome*.deb || true 1> /dev/null
          apt-get -q install --yes -f 1> /dev/null
          ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Install Maven
        run: |
          apt-get -q install --yes maven 1> /dev/null

      - name: Install NPM for react front end
        run: |
          cd react
          npm install

      #Remember that these "runs" are organized into processes, when they end, so do their children
      - name: Run React and Selenium
        run: |
          cd react
          npm start &
          cd ../SeleniumWithReact
          mvn -q clean verify -Dtestng.dtd.http=true
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber.json"

      - name: Deploy Selenium/Cucumber report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/cucumber-report-html/cucumber-html-reports

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
